### ISSUE TITLE
Slugify needs Unicode not String

### ISSUE THREAD

**Issue by Puddinglord** [encounterplus/support-tools#2]
While I was trying to convert some FG modules into Encounter+ modules I ran into the issue where anytime a variable would need to be slugified it was erroring out saying that it needs to be Unicode instead of a string. 

I have a working copy now that does convert FG to Encounter+ successfully and will clean it up and submit a pull request fixing that issue.

**Comment by jurex** [comment]
it is best to use python3 and `python-slugify` library instead of `slugify`
```
pip3 uninstall slugify
pip3 install python-slugify
```

**Comment by Puddinglord** [comment]
Thanks, again just mentioning these details should be in the readme.

**Comment by jurex** [comment]
Readme updated, thanks!

**Comment by 3lm3r** [comment]
why forcing slugify? Does Encounter+ doesn't slugify during import?

**Comment by jurex** [comment]
@3lm3r It does, if slug is not present. But I'm using it here when referencing map marker. 

https://github.com/encounterplus/support-tools/blame/23ba2fe1af2f89816bbbfbbe9be5fc4bb57eeebb/parsers/fantasygrounds.py#L183
