### ISSUE TITLE
unpack_archive not working (workaround included)

### ISSUE THREAD

**Issue by Puddinglord** [encounterplus/support-tools#3]
I have run into the problem were running the script on a .mod file from FG it would error out saying that it couldn't unpack it.

My fix is a bad one but got it working which is unzip the mod file manually and point the script to the unzipped folders name which does work.

I will continue trying to get it to unpack itself but this is a workaround for now so people can convert modules.

**Comment by jurex** [comment]
`unpack_archive` is not working properly with python2.7, but it should be working with python3

**Comment by Puddinglord** [comment]
Thanks, with that then this issue can be closed. Also, I think it would be worth mentioning these details in the readme.

**Comment by jurex** [comment]
Readme updated, thanks!
