### ISSUE TITLE
I get an error when I try to run the script

### ISSUE THREAD

**Issue by pedetentous** [encounterplus/support-tools#4]
Hello! I don't know if anyone else has had this issue...

I've installed Python3 using Homebrew.
I've installed both dependencies using pip3.
I've set my .bash_profile to contain:
alias python='python3'
So "python --version" returns "Python 3.7.4"

I run the following command:
./convert.py ~/Downloads/Module.mod --name "My Module"

And I get this error:
<<
Traceback (most recent call last):
  File "./convert.py", line 32, in <module>
    from slugify import slugify
ImportError: No module named slugify
>>

Is there something I am doing wrong?? Thank you so much for your time!

~Ped

**Comment by jurex** [comment]
Hi you need to install slugify module for python 3.

```pip3 install natsort
pip3 install python-slugify```

**Comment by pedetentous** [comment]
I did have them both installed, but running the command with "python3" worked! Thank you so much. I think that your app is brilliant!!

~Ped
